'use client'

import { Badge } from '@/components/ui/badge'

const statusColors: Record<string, string> = {
  PENDING: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  REVIEWED: 'bg-blue-100 text-blue-800 border-blue-200',
  QUOTED: 'bg-indigo-100 text-indigo-800 border-indigo-200',
  ACCEPTED: 'bg-green-100 text-green-800 border-green-200',
  REJECTED: 'bg-red-100 text-red-800 border-red-200',
  EXPIRED: 'bg-gray-100 text-gray-800 border-gray-200',
  DRAFT: 'bg-slate-100 text-slate-800 border-slate-200',
  SENT: 'bg-green-100 text-green-800 border-green-200',
  CONFIRMED: 'bg-green-100 text-green-800 border-green-200',
  ACOMPTE_RECU: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  PAIEMENT_A_LIVRAISON: 'bg-amber-100 text-amber-800 border-amber-200',
  IN_PRODUCTION: 'bg-orange-100 text-orange-800 border-orange-200',
  READY: 'bg-cyan-100 text-cyan-800 border-cyan-200',
  SHIPPED: 'bg-purple-100 text-purple-800 border-purple-200',
  DELIVERED: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  CANCELLED: 'bg-red-100 text-red-800 border-red-200',
  PAID: 'bg-green-100 text-green-800 border-green-200',
  EN_ATTENTE: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  PAYE: 'bg-green-100 text-green-800 border-green-200',
  ECHEC: 'bg-red-100 text-red-800 border-red-200',
  ANNULE: 'bg-gray-100 text-gray-800 border-gray-200',
  REMBOURSE: 'bg-blue-100 text-blue-800 border-blue-200',
  PARTIAL: 'bg-orange-100 text-orange-800 border-orange-200',
  OVERDUE: 'bg-red-100 text-red-800 border-red-200',
  A_PREPARER: 'bg-blue-100 text-blue-800 border-blue-200',
  PRETE: 'bg-cyan-100 text-cyan-800 border-cyan-200',
  EN_LIVRAISON: 'bg-purple-100 text-purple-800 border-purple-200',
  LIVREE: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  RESERVATION: 'bg-indigo-100 text-indigo-800 border-indigo-200',
  RELEASE: 'bg-teal-100 text-teal-800 border-teal-200',
  ADJUSTMENT: 'bg-amber-100 text-amber-800 border-amber-200',
  FAILED: 'bg-red-100 text-red-800 border-red-200',
  DEPOSIT: 'bg-blue-100 text-blue-800 border-blue-200',
  BALANCE: 'bg-orange-100 text-orange-800 border-orange-200',
  FULL: 'bg-green-100 text-green-800 border-green-200',
  ON_DELIVERY: 'bg-slate-100 text-slate-800 border-slate-200',
  DEPOSIT_PLUS_BALANCE: 'bg-indigo-100 text-indigo-800 border-indigo-200',
  NOUVELLE_COMMANDE: 'bg-blue-100 text-blue-800 border-blue-200',
  CLIENT_CONTACTE: 'bg-cyan-100 text-cyan-800 border-cyan-200',
  DEVIS_EN_PREPARATION: 'bg-amber-100 text-amber-800 border-amber-200',
  DEVIS_ENVOYE: 'bg-purple-100 text-purple-800 border-purple-200',
  DEVIS_ACCEPTE: 'bg-green-100 text-green-800 border-green-200',
  COMMANDE_CONFIRMEE: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  EN_PREPARATION: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  DEVIS_REFUSE: 'bg-red-100 text-red-800 border-red-200',
  ANNULEE: 'bg-gray-100 text-gray-800 border-gray-200',
}

const statusLabels: Record<string, string> = {
  PENDING: 'En attente',
  REVIEWED: 'Revue',
  QUOTED: 'Devis cree',
  ACCEPTED: 'Accepte',
  REJECTED: 'Rejete',
  EXPIRED: 'Expire',
  DRAFT: 'Brouillon',
  SENT: 'Envoye',
  CONFIRMED: 'Confirme',
  ACOMPTE_RECU: 'Acompte recu',
  PAIEMENT_A_LIVRAISON: 'Paiement a la livraison',
  IN_PRODUCTION: 'En production',
  READY: 'Pret',
  SHIPPED: 'Expédie',
  DELIVERED: 'Livre',
  CANCELLED: 'Annule',
  PAID: 'Paye',
  EN_ATTENTE: 'En attente',
  PAYE: 'Paye',
  ECHEC: 'Echec',
  ANNULE: 'Annule',
  REMBOURSE: 'Rembourse',
  PARTIAL: 'Partiel',
  OVERDUE: 'En retard',
  A_PREPARER: 'A preparer',
  PRETE: 'Prete',
  EN_LIVRAISON: 'En livraison',
  LIVREE: 'Livree',
  RESERVATION: 'Reservation',
  RELEASE: 'Liberation',
  ADJUSTMENT: 'Ajustement',
  FAILED: 'Echoue',
  DEPOSIT: 'Acompte',
  BALANCE: 'Solde',
  FULL: 'Paiement complet',
  ON_DELIVERY: 'A la livraison',
  DEPOSIT_PLUS_BALANCE: 'Acompte + Solde',
  NOUVELLE_COMMANDE: 'Nouvelle commande',
  CLIENT_CONTACTE: 'Client contacte',
  DEVIS_EN_PREPARATION: 'Devis en preparation',
  DEVIS_ENVOYE: 'Devis envoye',
  DEVIS_ACCEPTE: 'Devis accepte',
  COMMANDE_CONFIRMEE: 'Commande confirmee',
  EN_PREPARATION: 'En preparation',
  DEVIS_REFUSE: 'Devis refuse',
  ANNULEE: 'Annulee',
}

export function StatusBadge({ status }: { status: string }) {
  const color = statusColors[status] ?? 'bg-gray-100 text-gray-800 border-gray-200'
  const label = statusLabels[status] ?? status

  return (
    <Badge variant="outline" className={color}>
      {label}
    </Badge>
  )
}